# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mensajes.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version # type: ignore
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'mensajes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emensajes.proto\x12\x07mensaje\"\x1e\n\x0binitBackend\x12\x0f\n\x07iniciar\x18\x01 \x01(\x08\"\x19\n\x08\x42usqueda\x12\r\n\x05texto\x18\x01 \x01(\t\"9\n\x08Pelicula\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x10\n\x08sinopsis\x18\x03 \x01(\t\":\n\x12Resultado_Busqueda\x12$\n\tpeliculas\x18\x01 \x03(\x0b\x32\x11.mensaje.Peliculab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensajes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITBACKEND']._serialized_start=27
  _globals['_INITBACKEND']._serialized_end=57
  _globals['_BUSQUEDA']._serialized_start=59
  _globals['_BUSQUEDA']._serialized_end=84
  _globals['_PELICULA']._serialized_start=86
  _globals['_PELICULA']._serialized_end=143
  _globals['_RESULTADO_BUSQUEDA']._serialized_start=145
  _globals['_RESULTADO_BUSQUEDA']._serialized_end=203
# @@protoc_insertion_point(module_scope)
