// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mensajes.proto
// Protobuf C++ Version: 5.27.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_mensajes_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_mensajes_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_mensajes_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_mensajes_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_mensajes_2eproto;
namespace mensaje {
class Busqueda;
struct BusquedaDefaultTypeInternal;
extern BusquedaDefaultTypeInternal _Busqueda_default_instance_;
class Pelicula;
struct PeliculaDefaultTypeInternal;
extern PeliculaDefaultTypeInternal _Pelicula_default_instance_;
class Resultado_Busqueda;
struct Resultado_BusquedaDefaultTypeInternal;
extern Resultado_BusquedaDefaultTypeInternal _Resultado_Busqueda_default_instance_;
class conexion;
struct conexionDefaultTypeInternal;
extern conexionDefaultTypeInternal _conexion_default_instance_;
}  // namespace mensaje
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace mensaje {

// ===================================================================


// -------------------------------------------------------------------

class conexion final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mensaje.conexion) */ {
 public:
  inline conexion() : conexion(nullptr) {}
  ~conexion() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR conexion(
      ::google::protobuf::internal::ConstantInitialized);

  inline conexion(const conexion& from) : conexion(nullptr, from) {}
  inline conexion(conexion&& from) noexcept
      : conexion(nullptr, std::move(from)) {}
  inline conexion& operator=(const conexion& from) {
    CopyFrom(from);
    return *this;
  }
  inline conexion& operator=(conexion&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const conexion& default_instance() {
    return *internal_default_instance();
  }
  static inline const conexion* internal_default_instance() {
    return reinterpret_cast<const conexion*>(
        &_conexion_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(conexion& a, conexion& b) { a.Swap(&b); }
  inline void Swap(conexion* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(conexion* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  conexion* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<conexion>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const conexion& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const conexion& from) { conexion::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(conexion* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "mensaje.conexion"; }

 protected:
  explicit conexion(::google::protobuf::Arena* arena);
  conexion(::google::protobuf::Arena* arena, const conexion& from);
  conexion(::google::protobuf::Arena* arena, conexion&& from) noexcept
      : conexion(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEstadoFieldNumber = 1,
  };
  // bool estado = 1;
  void clear_estado() ;
  bool estado() const;
  void set_estado(bool value);

  private:
  bool _internal_estado() const;
  void _internal_set_estado(bool value);

  public:
  // @@protoc_insertion_point(class_scope:mensaje.conexion)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_conexion_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const conexion& from_msg);
    bool estado_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mensajes_2eproto;
};
// -------------------------------------------------------------------

class Pelicula final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mensaje.Pelicula) */ {
 public:
  inline Pelicula() : Pelicula(nullptr) {}
  ~Pelicula() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Pelicula(
      ::google::protobuf::internal::ConstantInitialized);

  inline Pelicula(const Pelicula& from) : Pelicula(nullptr, from) {}
  inline Pelicula(Pelicula&& from) noexcept
      : Pelicula(nullptr, std::move(from)) {}
  inline Pelicula& operator=(const Pelicula& from) {
    CopyFrom(from);
    return *this;
  }
  inline Pelicula& operator=(Pelicula&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Pelicula& default_instance() {
    return *internal_default_instance();
  }
  static inline const Pelicula* internal_default_instance() {
    return reinterpret_cast<const Pelicula*>(
        &_Pelicula_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Pelicula& a, Pelicula& b) { a.Swap(&b); }
  inline void Swap(Pelicula* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Pelicula* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Pelicula* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Pelicula>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Pelicula& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Pelicula& from) { Pelicula::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Pelicula* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "mensaje.Pelicula"; }

 protected:
  explicit Pelicula(::google::protobuf::Arena* arena);
  Pelicula(::google::protobuf::Arena* arena, const Pelicula& from);
  Pelicula(::google::protobuf::Arena* arena, Pelicula&& from) noexcept
      : Pelicula(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTituloFieldNumber = 1,
    kTagFieldNumber = 2,
    kSinopsisFieldNumber = 3,
  };
  // string titulo = 1;
  void clear_titulo() ;
  const std::string& titulo() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_titulo(Arg_&& arg, Args_... args);
  std::string* mutable_titulo();
  PROTOBUF_NODISCARD std::string* release_titulo();
  void set_allocated_titulo(std::string* value);

  private:
  const std::string& _internal_titulo() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_titulo(
      const std::string& value);
  std::string* _internal_mutable_titulo();

  public:
  // string tag = 2;
  void clear_tag() ;
  const std::string& tag() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_tag(Arg_&& arg, Args_... args);
  std::string* mutable_tag();
  PROTOBUF_NODISCARD std::string* release_tag();
  void set_allocated_tag(std::string* value);

  private:
  const std::string& _internal_tag() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tag(
      const std::string& value);
  std::string* _internal_mutable_tag();

  public:
  // string sinopsis = 3;
  void clear_sinopsis() ;
  const std::string& sinopsis() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sinopsis(Arg_&& arg, Args_... args);
  std::string* mutable_sinopsis();
  PROTOBUF_NODISCARD std::string* release_sinopsis();
  void set_allocated_sinopsis(std::string* value);

  private:
  const std::string& _internal_sinopsis() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sinopsis(
      const std::string& value);
  std::string* _internal_mutable_sinopsis();

  public:
  // @@protoc_insertion_point(class_scope:mensaje.Pelicula)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      42, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Pelicula_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Pelicula& from_msg);
    ::google::protobuf::internal::ArenaStringPtr titulo_;
    ::google::protobuf::internal::ArenaStringPtr tag_;
    ::google::protobuf::internal::ArenaStringPtr sinopsis_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mensajes_2eproto;
};
// -------------------------------------------------------------------

class Busqueda final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mensaje.Busqueda) */ {
 public:
  inline Busqueda() : Busqueda(nullptr) {}
  ~Busqueda() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Busqueda(
      ::google::protobuf::internal::ConstantInitialized);

  inline Busqueda(const Busqueda& from) : Busqueda(nullptr, from) {}
  inline Busqueda(Busqueda&& from) noexcept
      : Busqueda(nullptr, std::move(from)) {}
  inline Busqueda& operator=(const Busqueda& from) {
    CopyFrom(from);
    return *this;
  }
  inline Busqueda& operator=(Busqueda&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Busqueda& default_instance() {
    return *internal_default_instance();
  }
  static inline const Busqueda* internal_default_instance() {
    return reinterpret_cast<const Busqueda*>(
        &_Busqueda_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Busqueda& a, Busqueda& b) { a.Swap(&b); }
  inline void Swap(Busqueda* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Busqueda* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Busqueda* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Busqueda>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Busqueda& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Busqueda& from) { Busqueda::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Busqueda* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "mensaje.Busqueda"; }

 protected:
  explicit Busqueda(::google::protobuf::Arena* arena);
  Busqueda(::google::protobuf::Arena* arena, const Busqueda& from);
  Busqueda(::google::protobuf::Arena* arena, Busqueda&& from) noexcept
      : Busqueda(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTextoFieldNumber = 1,
  };
  // string texto = 1;
  void clear_texto() ;
  const std::string& texto() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_texto(Arg_&& arg, Args_... args);
  std::string* mutable_texto();
  PROTOBUF_NODISCARD std::string* release_texto();
  void set_allocated_texto(std::string* value);

  private:
  const std::string& _internal_texto() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_texto(
      const std::string& value);
  std::string* _internal_mutable_texto();

  public:
  // @@protoc_insertion_point(class_scope:mensaje.Busqueda)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      30, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Busqueda_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Busqueda& from_msg);
    ::google::protobuf::internal::ArenaStringPtr texto_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mensajes_2eproto;
};
// -------------------------------------------------------------------

class Resultado_Busqueda final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:mensaje.Resultado_Busqueda) */ {
 public:
  inline Resultado_Busqueda() : Resultado_Busqueda(nullptr) {}
  ~Resultado_Busqueda() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Resultado_Busqueda(
      ::google::protobuf::internal::ConstantInitialized);

  inline Resultado_Busqueda(const Resultado_Busqueda& from) : Resultado_Busqueda(nullptr, from) {}
  inline Resultado_Busqueda(Resultado_Busqueda&& from) noexcept
      : Resultado_Busqueda(nullptr, std::move(from)) {}
  inline Resultado_Busqueda& operator=(const Resultado_Busqueda& from) {
    CopyFrom(from);
    return *this;
  }
  inline Resultado_Busqueda& operator=(Resultado_Busqueda&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Resultado_Busqueda& default_instance() {
    return *internal_default_instance();
  }
  static inline const Resultado_Busqueda* internal_default_instance() {
    return reinterpret_cast<const Resultado_Busqueda*>(
        &_Resultado_Busqueda_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Resultado_Busqueda& a, Resultado_Busqueda& b) { a.Swap(&b); }
  inline void Swap(Resultado_Busqueda* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Resultado_Busqueda* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Resultado_Busqueda* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Resultado_Busqueda>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Resultado_Busqueda& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Resultado_Busqueda& from) { Resultado_Busqueda::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Resultado_Busqueda* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "mensaje.Resultado_Busqueda"; }

 protected:
  explicit Resultado_Busqueda(::google::protobuf::Arena* arena);
  Resultado_Busqueda(::google::protobuf::Arena* arena, const Resultado_Busqueda& from);
  Resultado_Busqueda(::google::protobuf::Arena* arena, Resultado_Busqueda&& from) noexcept
      : Resultado_Busqueda(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPeliculasFieldNumber = 1,
  };
  // repeated .mensaje.Pelicula peliculas = 1;
  int peliculas_size() const;
  private:
  int _internal_peliculas_size() const;

  public:
  void clear_peliculas() ;
  ::mensaje::Pelicula* mutable_peliculas(int index);
  ::google::protobuf::RepeatedPtrField<::mensaje::Pelicula>* mutable_peliculas();

  private:
  const ::google::protobuf::RepeatedPtrField<::mensaje::Pelicula>& _internal_peliculas() const;
  ::google::protobuf::RepeatedPtrField<::mensaje::Pelicula>* _internal_mutable_peliculas();
  public:
  const ::mensaje::Pelicula& peliculas(int index) const;
  ::mensaje::Pelicula* add_peliculas();
  const ::google::protobuf::RepeatedPtrField<::mensaje::Pelicula>& peliculas() const;
  // @@protoc_insertion_point(class_scope:mensaje.Resultado_Busqueda)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Resultado_Busqueda_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Resultado_Busqueda& from_msg);
    ::google::protobuf::RepeatedPtrField< ::mensaje::Pelicula > peliculas_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mensajes_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// conexion

// bool estado = 1;
inline void conexion::clear_estado() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.estado_ = false;
}
inline bool conexion::estado() const {
  // @@protoc_insertion_point(field_get:mensaje.conexion.estado)
  return _internal_estado();
}
inline void conexion::set_estado(bool value) {
  _internal_set_estado(value);
  // @@protoc_insertion_point(field_set:mensaje.conexion.estado)
}
inline bool conexion::_internal_estado() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.estado_;
}
inline void conexion::_internal_set_estado(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.estado_ = value;
}

// -------------------------------------------------------------------

// Busqueda

// string texto = 1;
inline void Busqueda::clear_texto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.texto_.ClearToEmpty();
}
inline const std::string& Busqueda::texto() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mensaje.Busqueda.texto)
  return _internal_texto();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Busqueda::set_texto(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.texto_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mensaje.Busqueda.texto)
}
inline std::string* Busqueda::mutable_texto() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_texto();
  // @@protoc_insertion_point(field_mutable:mensaje.Busqueda.texto)
  return _s;
}
inline const std::string& Busqueda::_internal_texto() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.texto_.Get();
}
inline void Busqueda::_internal_set_texto(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.texto_.Set(value, GetArena());
}
inline std::string* Busqueda::_internal_mutable_texto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.texto_.Mutable( GetArena());
}
inline std::string* Busqueda::release_texto() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mensaje.Busqueda.texto)
  return _impl_.texto_.Release();
}
inline void Busqueda::set_allocated_texto(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.texto_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.texto_.IsDefault()) {
          _impl_.texto_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mensaje.Busqueda.texto)
}

// -------------------------------------------------------------------

// Pelicula

// string titulo = 1;
inline void Pelicula::clear_titulo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.titulo_.ClearToEmpty();
}
inline const std::string& Pelicula::titulo() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mensaje.Pelicula.titulo)
  return _internal_titulo();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Pelicula::set_titulo(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.titulo_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mensaje.Pelicula.titulo)
}
inline std::string* Pelicula::mutable_titulo() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_titulo();
  // @@protoc_insertion_point(field_mutable:mensaje.Pelicula.titulo)
  return _s;
}
inline const std::string& Pelicula::_internal_titulo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.titulo_.Get();
}
inline void Pelicula::_internal_set_titulo(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.titulo_.Set(value, GetArena());
}
inline std::string* Pelicula::_internal_mutable_titulo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.titulo_.Mutable( GetArena());
}
inline std::string* Pelicula::release_titulo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mensaje.Pelicula.titulo)
  return _impl_.titulo_.Release();
}
inline void Pelicula::set_allocated_titulo(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.titulo_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.titulo_.IsDefault()) {
          _impl_.titulo_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mensaje.Pelicula.titulo)
}

// string tag = 2;
inline void Pelicula::clear_tag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tag_.ClearToEmpty();
}
inline const std::string& Pelicula::tag() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mensaje.Pelicula.tag)
  return _internal_tag();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Pelicula::set_tag(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tag_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mensaje.Pelicula.tag)
}
inline std::string* Pelicula::mutable_tag() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_tag();
  // @@protoc_insertion_point(field_mutable:mensaje.Pelicula.tag)
  return _s;
}
inline const std::string& Pelicula::_internal_tag() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tag_.Get();
}
inline void Pelicula::_internal_set_tag(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tag_.Set(value, GetArena());
}
inline std::string* Pelicula::_internal_mutable_tag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tag_.Mutable( GetArena());
}
inline std::string* Pelicula::release_tag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mensaje.Pelicula.tag)
  return _impl_.tag_.Release();
}
inline void Pelicula::set_allocated_tag(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tag_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.tag_.IsDefault()) {
          _impl_.tag_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mensaje.Pelicula.tag)
}

// string sinopsis = 3;
inline void Pelicula::clear_sinopsis() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sinopsis_.ClearToEmpty();
}
inline const std::string& Pelicula::sinopsis() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mensaje.Pelicula.sinopsis)
  return _internal_sinopsis();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Pelicula::set_sinopsis(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sinopsis_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:mensaje.Pelicula.sinopsis)
}
inline std::string* Pelicula::mutable_sinopsis() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sinopsis();
  // @@protoc_insertion_point(field_mutable:mensaje.Pelicula.sinopsis)
  return _s;
}
inline const std::string& Pelicula::_internal_sinopsis() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sinopsis_.Get();
}
inline void Pelicula::_internal_set_sinopsis(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sinopsis_.Set(value, GetArena());
}
inline std::string* Pelicula::_internal_mutable_sinopsis() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.sinopsis_.Mutable( GetArena());
}
inline std::string* Pelicula::release_sinopsis() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:mensaje.Pelicula.sinopsis)
  return _impl_.sinopsis_.Release();
}
inline void Pelicula::set_allocated_sinopsis(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sinopsis_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sinopsis_.IsDefault()) {
          _impl_.sinopsis_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mensaje.Pelicula.sinopsis)
}

// -------------------------------------------------------------------

// Resultado_Busqueda

// repeated .mensaje.Pelicula peliculas = 1;
inline int Resultado_Busqueda::_internal_peliculas_size() const {
  return _internal_peliculas().size();
}
inline int Resultado_Busqueda::peliculas_size() const {
  return _internal_peliculas_size();
}
inline void Resultado_Busqueda::clear_peliculas() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.peliculas_.Clear();
}
inline ::mensaje::Pelicula* Resultado_Busqueda::mutable_peliculas(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:mensaje.Resultado_Busqueda.peliculas)
  return _internal_mutable_peliculas()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::mensaje::Pelicula>* Resultado_Busqueda::mutable_peliculas()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:mensaje.Resultado_Busqueda.peliculas)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_peliculas();
}
inline const ::mensaje::Pelicula& Resultado_Busqueda::peliculas(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:mensaje.Resultado_Busqueda.peliculas)
  return _internal_peliculas().Get(index);
}
inline ::mensaje::Pelicula* Resultado_Busqueda::add_peliculas() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::mensaje::Pelicula* _add = _internal_mutable_peliculas()->Add();
  // @@protoc_insertion_point(field_add:mensaje.Resultado_Busqueda.peliculas)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::mensaje::Pelicula>& Resultado_Busqueda::peliculas() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:mensaje.Resultado_Busqueda.peliculas)
  return _internal_peliculas();
}
inline const ::google::protobuf::RepeatedPtrField<::mensaje::Pelicula>&
Resultado_Busqueda::_internal_peliculas() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.peliculas_;
}
inline ::google::protobuf::RepeatedPtrField<::mensaje::Pelicula>*
Resultado_Busqueda::_internal_mutable_peliculas() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.peliculas_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace mensaje


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_mensajes_2eproto_2epb_2eh
